site:
  title: Java news [Antora Demo site]
  start_page: entrance-doc::index.adoc
  robots: allow
content:
  sources:
    - url: ./
      start_path: entrance-doc
      branches: HEAD
    - url: ./
      start_path: component-java24
      branches: HEAD
    - url: ./
      start_path: component-java25
      branches: HEAD

asciidoc:
  attributes:
    experimental: ''
    hide-uri-scheme: '@'
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    table-frame: 'none@'
    table-grid: 'rows@'
  extensions:
    - './entrance-doc/extensions/card-block.js'

antora:
  extensions:
    - '/usr/local/lib/node_modules/@antora/lunr-extension'

ui:
  bundle:
    #Permet de tester le site avec le ui-bundle par defaut d'antora
    #url: "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable"
    #snapshot: true

    #Permet de debugger en local la ui
    #url: ./ui-bundle

    #Permet d'utiliser un bundle prebuild'
    url: "https://github.com/FredMencier/antora-ui-spring/releases/download/1.0.0/ui-bundle.zip"

    #Permet de tester le site avec une ui-bundle embarqu√©e dans l'image docker
    #url: '/usr/local/lib/node_modules/@antora/ui-bundle'

output:
  dir: ./generated-site
